// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgr6Fcg_cI3y_4MhAho52W0RNnKbjNhc',
    appId: '1:440073782621:web:a8adf8a443665d357a94b4',
    messagingSenderId: '440073782621',
    projectId: 'go-india-d3676',
    authDomain: 'go-india-d3676.firebaseapp.com',
    storageBucket: 'go-india-d3676.appspot.com',
    measurementId: 'G-Q5RN1LY54B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcutrcE504JpgtCoLnNxPd3ve7N6yf0KU',
    appId: '1:440073782621:android:2d4eb7f244af61bc7a94b4',
    messagingSenderId: '440073782621',
    projectId: 'go-india-d3676',
    storageBucket: 'go-india-d3676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpDABUTtznNBaJ-exw9Ml74vqqj8C-YA',
    appId: '1:440073782621:ios:0d39b1c493787e8f7a94b4',
    messagingSenderId: '440073782621',
    projectId: 'go-india-d3676',
    storageBucket: 'go-india-d3676.appspot.com',
    iosBundleId: 'com.goindia.goIndia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpDABUTtznNBaJ-exw9Ml74vqqj8C-YA',
    appId: '1:440073782621:ios:61692dfaf39295e57a94b4',
    messagingSenderId: '440073782621',
    projectId: 'go-india-d3676',
    storageBucket: 'go-india-d3676.appspot.com',
    iosBundleId: 'com.goindia.goIndia.RunnerTests',
  );
}
